const fact = [
    { "Average Temperature in New York": "22°C", "Total Rainfall in New York": "150mm", "Humidity in New York": "60%" },
    { "Average Temperature in Los Angeles": "25°C", "Total Rainfall in Los Angeles": "75mm", "Humidity in Los Angeles": "50%" },
    { "Average Temperature in Chicago": "20°C", "Total Rainfall in Chicago": "200mm", "Humidity in Chicago": "70%" },
    { "Average Temperature in Houston": "28°C", "Total Rainfall in Houston": "120mm", "Humidity in Houston": "80%" },
    { "Average Temperature in Phoenix": "35°C", "Total Rainfall in Phoenix": "20mm", "Humidity in Phoenix": "30%" },
    { "Population of New York": "8.3M", "Population Density of New York": "10,000/km^2", "Growth Rate of New York": "0.5%" },
    { "Population of Los Angeles": "4M", "Population Density of Los Angeles": "3,200/km^2", "Growth Rate of Los Angeles": "0.3%" },
    { "Population of Chicago": "2.7M", "Population Density of Chicago": "4,500/km^2", "Growth Rate of Chicago": "0.2%" },
    { "Population of Houston": "2.3M", "Population Density of Houston": "1,300/km^2", "Growth Rate of Houston": "1.0%" },
    { "Population of Phoenix": "1.7M", "Population Density of Phoenix": "1,200/km^2", "Growth Rate of Phoenix": "1.5%" },
    { "GDP of USA": "$21T", "GDP Growth Rate of USA": "2.3%", "GDP per Capita of USA": "$65,000" },
    { "GDP of China": "$14T", "GDP Growth Rate of China": "6.1%", "GDP per Capita of China": "$10,000" },
    { "GDP of Japan": "$5T", "GDP Growth Rate of Japan": "0.7%", "GDP per Capita of Japan": "$40,000" },
    { "GDP of Germany": "$4T", "GDP Growth Rate of Germany": "1.5%", "GDP per Capita of Germany": "$50,000" },
    { "GDP of India": "$2.9T", "GDP Growth Rate of India": "5.0%", "GDP per Capita of India": "$2,100" },
    { "Life Expectancy in USA": "79 years", "Infant Mortality Rate in USA": "5.6/1000", "Birth Rate in USA": "12/1000" },
    { "Life Expectancy in Canada": "82 years", "Infant Mortality Rate in Canada": "4.3/1000", "Birth Rate in Canada": "10/1000" },
    { "Life Expectancy in UK": "81 years", "Infant Mortality Rate in UK": "3.9/1000", "Birth Rate in UK": "11/1000" },
    { "Life Expectancy in Australia": "83 years", "Infant Mortality Rate in Australia": "3.1/1000", "Birth Rate in Australia": "13/1000" },
    { "Life Expectancy in Germany": "81 years", "Infant Mortality Rate in Germany": "3.2/1000", "Birth Rate in Germany": "9/1000" },
    { "Electricity Production in USA": "4,000 TWh", "Renewable Energy Share in USA": "17%", "CO2 Emissions in USA": "5.3 GT" },
    { "Electricity Production in China": "7,000 TWh", "Renewable Energy Share in China": "25%", "CO2 Emissions in China": "10 GT" },
    { "Electricity Production in India": "1,600 TWh", "Renewable Energy Share in India": "15%", "CO2 Emissions in India": "2.6 GT" },
    { "Electricity Production in Russia": "1,100 TWh", "Renewable Energy Share in Russia": "5%", "CO2 Emissions in Russia": "1.5 GT" },
    { "Electricity Production in Brazil": "600 TWh", "Renewable Energy Share in Brazil": "80%", "CO2 Emissions in Brazil": "0.5 GT" },
    { "Internet Penetration in USA": "89%", "Smartphone Penetration in USA": "81%", "Average Internet Speed in USA": "150 Mbps" },
    { "Internet Penetration in Canada": "91%", "Smartphone Penetration in Canada": "83%", "Average Internet Speed in Canada": "120 Mbps" },
    { "Internet Penetration in UK": "95%", "Smartphone Penetration in UK": "87%", "Average Internet Speed in UK": "100 Mbps" },
    { "Internet Penetration in Germany": "93%", "Smartphone Penetration in Germany": "85%", "Average Internet Speed in Germany": "110 Mbps" },
    { "Internet Penetration in Japan": "92%", "Smartphone Penetration in Japan": "86%", "Average Internet Speed in Japan": "200 Mbps" },
    { "Literacy Rate in USA": "99%", "School Enrollment in USA": "95%", "Graduation Rate in USA": "88%" },
    { "Literacy Rate in Canada": "99%", "School Enrollment in Canada": "96%", "Graduation Rate in Canada": "90%" },
    { "Literacy Rate in UK": "99%", "School Enrollment in UK": "94%", "Graduation Rate in UK": "85%" },
    { "Literacy Rate in Australia": "99%", "School Enrollment in Australia": "93%", "Graduation Rate in Australia": "86%" },
    { "Literacy Rate in Germany": "99%", "School Enrollment in Germany": "92%", "Graduation Rate in Germany": "87%" },
    { "Total Exports of USA": "$2.5T", "Total Imports of USA": "$3.1T", "Trade Balance of USA": "-$600B" },
    { "Total Exports of China": "$2.6T", "Total Imports of China": "$2.3T", "Trade Balance of China": "$300B" },
    { "Total Exports of Germany": "$1.5T", "Total Imports of Germany": "$1.2T", "Trade Balance of Germany": "$300B" },
    { "Total Exports of Japan": "$700B", "Total Imports of Japan": "$800B", "Trade Balance of Japan": "-$100B" },
    { "Total Exports of India": "$330B", "Total Imports of India": "$500B", "Trade Balance of India": "-$170B" },
    { "Forest Area in USA": "3M km^2", "Protected Areas in USA": "1M km^2", "Deforestation Rate in USA": "0.3%" },
    { "Forest Area in Brazil": "4M km^2", "Protected Areas in Brazil": "2M km^2", "Deforestation Rate in Brazil": "1.0%" },
    { "Forest Area in Canada": "3.5M km^2", "Protected Areas in Canada": "1.5M km^2", "Deforestation Rate in Canada": "0.2%" },
    { "Forest Area in Russia": "8M km^2", "Protected Areas in Russia": "3M km^2", "Deforestation Rate in Russia": "0.1%" },
    { "Forest Area in Australia": "1.5M km^2", "Protected Areas in Australia": "0.5M km^2", "Deforestation Rate in Australia": "0.4%" },
    { "Average Age in USA": "38 years", "Median Income in USA": "$68,000", "Poverty Rate in USA": "10.5%" },
    { "Average Age in Canada": "41 years", "Median Income in Canada": "$60,000", "Poverty Rate in Canada": "9.5%" },
    { "Average Age in UK": "40 years", "Median Income in UK": "$45,000", "Poverty Rate in UK": "11.0%" },
    { "Average Age in Germany": "45 years", "Median Income in Germany": "$50,000", "Poverty Rate in Germany": "10.0%" },
    { "Average Age in Japan": "47 years", "Median Income in Japan": "$40,000", "Poverty Rate in Japan": "15.7%" },
    { "Unemployment Rate in USA": "6.0%", "Labor Force Participation Rate in USA": "61%", "Employment Rate in USA": "58%" },
    { "Unemployment Rate in Canada": "5.5%", "Labor Force Participation Rate in Canada": "65%", "Employment Rate in Canada": "61%" },
    { "Unemployment Rate in UK": "4.5%", "Labor Force Participation Rate in UK": "63%", "Employment Rate in UK": "60%" },
    { "Unemployment Rate in Germany": "4.0%", "Labor Force Participation Rate in Germany": "66%", "Employment Rate in Germany": "64%" },
    { "Unemployment Rate in Australia": "5.0%", "Labor Force Participation Rate in Australia": "64%", "Employment Rate in Australia": "61%" },
    { "Inflation Rate in USA": "2.0%", "Consumer Price Index in USA": "260", "Producer Price Index in USA": "220" },
    { "Inflation Rate in Canada": "1.5%", "Consumer Price Index in Canada": "140", "Producer Price Index in Canada": "130" },
    { "Inflation Rate in UK": "1.8%", "Consumer Price Index in UK": "110", "Producer Price Index in UK": "100" },
    { "Inflation Rate in Germany": "1.2%", "Consumer Price Index in Germany": "120", "Producer Price Index in Germany": "110" },
    { "Inflation Rate in Australia": "2.5%", "Consumer Price Index in Australia": "130", "Producer Price Index in Australia": "120" },
    { "Crime Rate in USA": "380/100,000", "Violent Crime Rate in USA": "380/100,000", "Property Crime Rate in USA": "2,100/100,000" },
    { "Crime Rate in Canada": "370/100,000", "Violent Crime Rate in Canada": "300/100,000", "Property Crime Rate in Canada": "2,000/100,000" },
    { "Crime Rate in UK": "450/100,000", "Violent Crime Rate in UK": "500/100,000", "Property Crime Rate in UK": "1,500/100,000" },
    { "Crime Rate in Germany": "300/100,000", "Violent Crime Rate in Germany": "200/100,000", "Property Crime Rate in Germany": "1,000/100,000" },
    { "Crime Rate in Australia": "400/100,000", "Violent Crime Rate in Australia": "400/100,000", "Property Crime Rate in Australia": "1,800/100,000" },
    { "Average House Price in USA": "$300,000", "Median Rent in USA": "$1,500/month", "Home Ownership Rate in USA": "65%" },
    { "Average House Price in Canada": "$400,000", "Median Rent in Canada": "$1,200/month", "Home Ownership Rate in Canada": "68%" },
    { "Average House Price in UK": "$350,000", "Median Rent in UK": "$1,000/month", "Home Ownership Rate in UK": "63%" },
    { "Average House Price in Germany": "$250,000", "Median Rent in Germany": "$900/month", "Home Ownership Rate in Germany": "55%" },
    { "Average House Price in Australia": "$500,000", "Median Rent in Australia": "$1,300/month", "Home Ownership Rate in Australia": "70%" },
    { "Average Commute Time in USA": "27 minutes", "Public Transport Usage in USA": "12%", "Car Ownership Rate in USA": "80%" },
    { "Average Commute Time in Canada": "25 minutes", "Public Transport Usage in Canada": "14%", "Car Ownership Rate in Canada": "82%" },
    { "Average Commute Time in UK": "30 minutes", "Public Transport Usage in UK": "16%", "Car Ownership Rate in UK": "75%" },
    { "Average Commute Time in Germany": "22 minutes", "Public Transport Usage in Germany": "20%", "Car Ownership Rate in Germany": "70%" },
    { "Average Commute Time in Australia": "28 minutes", "Public Transport Usage in Australia": "10%", "Car Ownership Rate in Australia": "85%" },
    { "Life Satisfaction in USA": "7.0", "Happiness Index in USA": "6.9", "Well-being Index in USA": "7.1" },
    { "Life Satisfaction in Canada": "7.5", "Happiness Index in Canada": "7.2", "Well-being Index in Canada": "7.4" },
    { "Life Satisfaction in UK": "7.2", "Happiness Index in UK": "7.0", "Well-being Index in UK": "7.3" },
    { "Life Satisfaction in Germany": "6.8", "Happiness Index in Germany": "6.5", "Well-being Index in Germany": "6.9" },
    { "Life Satisfaction in Australia": "7.6", "Happiness Index in Australia": "7.4", "Well-being Index in Australia": "7.5" }
]

const false_fact = [
    { "Average Temperature in New York": "35°F", "Total Rainfall in New York": "50mm", "Humidity in New York": "30%" },
    { "Average Temperature in Los Angeles": "15°C", "Total Rainfall in Los Angeles": "200mm", "Humidity in Los Angeles": "70%" },
    { "Average Temperature in Chicago": "5°C", "Total Rainfall in Chicago": "500mm", "Humidity in Chicago": "20%" },
    { "Average Temperature in Houston": "10°C", "Total Rainfall in Houston": "300mm", "Humidity in Houston": "40%" },
    { "Average Temperature in Phoenix": "20°C", "Total Rainfall in Phoenix": "100mm", "Humidity in Phoenix": "60%" },
    { "Population of New York": "5M", "Population Density of New York": "5,000/km^2", "Growth Rate of New York": "1.5%" },
    { "Population of Los Angeles": "10M", "Population Density of Los Angeles": "1,000/km^2", "Growth Rate of Los Angeles": "2.3%" },
    { "Population of Chicago": "1M", "Population Density of Chicago": "1,000/km^2", "Growth Rate of Chicago": "0.5%" },
    { "Population of Houston": "5M", "Population Density of Houston": "2,500/km^2", "Growth Rate of Houston": "3.0%" },
    { "Population of Phoenix": "500K", "Population Density of Phoenix": "2,000/km^2", "Growth Rate of Phoenix": "0.2%" },
    { "GDP of USA": "$10T", "GDP Growth Rate of USA": "5.0%", "GDP per Capita of USA": "$30,000" },
    { "GDP of China": "$5T", "GDP Growth Rate of China": "2.0%", "GDP per Capita of China": "$5,000" },
    { "GDP of Japan": "$10T", "GDP Growth Rate of Japan": "5.0%", "GDP per Capita of Japan": "$20,000" },
    { "GDP of Germany": "$8T", "GDP Growth Rate of Germany": "3.5%", "GDP per Capita of Germany": "$100,000" },
    { "GDP of India": "$1T", "GDP Growth Rate of India": "1.0%", "GDP per Capita of India": "$500" },
    { "Life Expectancy in USA": "65 years", "Infant Mortality Rate in USA": "15/1000", "Birth Rate in USA": "5/1000" },
    { "Life Expectancy in Canada": "70 years", "Infant Mortality Rate in Canada": "10/1000", "Birth Rate in Canada": "7/1000" },
    { "Life Expectancy in UK": "60 years", "Infant Mortality Rate in UK": "20/1000", "Birth Rate in UK": "8/1000" },
    { "Life Expectancy in Australia": "75 years", "Infant Mortality Rate in Australia": "12/1000", "Birth Rate in Australia": "9/1000" },
    { "Life Expectancy in Germany": "67 years", "Infant Mortality Rate in Germany": "25/1000", "Birth Rate in Germany": "3/1000" },
    { "Electricity Production in USA": "1,000 TWh", "Renewable Energy Share in USA": "10%", "CO2 Emissions in USA": "1.3 GT" },
    { "Electricity Production in China": "3,000 TWh", "Renewable Energy Share in China": "5%", "CO2 Emissions in China": "4 GT" },
    { "Electricity Production in India": "500 TWh", "Renewable Energy Share in India": "2%", "CO2 Emissions in India": "1 GT" },
    { "Electricity Production in Russia": "300 TWh", "Renewable Energy Share in Russia": "10%", "CO2 Emissions in Russia": "3 GT" },
    { "Electricity Production in Brazil": "200 TWh", "Renewable Energy Share in Brazil": "50%", "CO2 Emissions in Brazil": "0.1 GT" },
    { "Internet Penetration in USA": "50%", "Smartphone Penetration in USA": "30%", "Average Internet Speed in USA": "50 Mbps" },
    { "Internet Penetration in Canada": "60%", "Smartphone Penetration in Canada": "40%", "Average Internet Speed in Canada": "40 Mbps" },
    { "Internet Penetration in UK": "55%", "Smartphone Penetration in UK": "35%", "Average Internet Speed in UK": "30 Mbps" },
    { "Internet Penetration in Germany": "45%", "Smartphone Penetration in Germany": "25%", "Average Internet Speed in Germany": "20 Mbps" },
    { "Internet Penetration in Japan": "65%", "Smartphone Penetration in Japan": "45%", "Average Internet Speed in Japan": "25 Mbps" },
    { "Literacy Rate in USA": "90%", "School Enrollment in USA": "75%", "Graduation Rate in USA": "50%" },
    { "Literacy Rate in Canada": "85%", "School Enrollment in Canada": "70%", "Graduation Rate in Canada": "60%" },
    { "Literacy Rate in UK": "88%", "School Enrollment in UK": "65%", "Graduation Rate in UK": "55%" },
    { "Literacy Rate in Australia": "80%", "School Enrollment in Australia": "60%", "Graduation Rate in Australia": "65%" },
    { "Literacy Rate in Germany": "82%", "School Enrollment in Germany": "55%", "Graduation Rate in Germany": "75%" },
    { "Total Exports of USA": "$5T", "Total Imports of USA": "$1T", "Trade Balance of USA": "$4T" },
    { "Total Exports of China": "$1T", "Total Imports of China": "$1T", "Trade Balance of China": "$0" },
    { "Total Exports of Germany": "$500B", "Total Imports of Germany": "$700B", "Trade Balance of Germany": "-$200B" },
    { "Total Exports of Japan": "$300B", "Total Imports of Japan": "$200B", "Trade Balance of Japan": "$100B" },
    { "Total Exports of India": "$100B", "Total Imports of India": "$300B", "Trade Balance of India": "-$200B" },
    { "Forest Area in USA": "1M km^2", "Protected Areas in USA": "500k km^2", "Deforestation Rate in USA": "5.0%" },
    { "Forest Area in Brazil": "2M km^2", "Protected Areas in Brazil": "1M km^2", "Deforestation Rate in Brazil": "10.0%" },
    { "Forest Area in Canada": "1.5M km^2", "Protected Areas in Canada": "500k km^2", "Deforestation Rate in Canada": "8.0%" },
    { "Forest Area in Russia": "4M km^2", "Protected Areas in Russia": "1M km^2", "Deforestation Rate in Russia": "2.0%" },
    { "Forest Area in Australia": "700k km^2", "Protected Areas in Australia": "300k km^2", "Deforestation Rate in Australia": "7.0%" },
    { "Average Age in USA": "25 years", "Median Income in USA": "$30,000", "Poverty Rate in USA": "20.5%" },
    { "Average Age in Canada": "35 years", "Median Income in Canada": "$20,000", "Poverty Rate in Canada": "15.5%" },
    { "Average Age in UK": "30 years", "Median Income in UK": "$35,000", "Poverty Rate in UK": "25.0%" },
    { "Average Age in Germany": "40 years", "Median Income in Germany": "$25,000", "Poverty Rate in Germany": "30.0%" },
    { "Average Age in Japan": "50 years", "Median Income in Japan": "$15,000", "Poverty Rate in Japan": "35.0%" },
    { "Unemployment Rate in USA": "10.0%", "Labor Force Participation Rate in USA": "50%", "Employment Rate in USA": "45%" },
    { "Unemployment Rate in Canada": "8.5%", "Labor Force Participation Rate in Canada": "55%", "Employment Rate in Canada": "50%" },
    { "Unemployment Rate in UK": "12.5%", "Labor Force Participation Rate in UK": "40%", "Employment Rate in UK": "35%" },
    { "Unemployment Rate in Germany": "9.0%", "Labor Force Participation Rate in Germany": "70%", "Employment Rate in Germany": "65%" },
    { "Unemployment Rate in Australia": "7.0%", "Labor Force Participation Rate in Australia": "60%", "Employment Rate in Australia": "55%" },
    { "Inflation Rate in USA": "5.0%", "Consumer Price Index in USA": "300", "Producer Price Index in USA": "250" },
    { "Inflation Rate in Canada": "4.5%", "Consumer Price Index in Canada": "150", "Producer Price Index in Canada": "140" },
    { "Inflation Rate in UK": "3.8%", "Consumer Price Index in UK": "120", "Producer Price Index in UK": "110" },
    { "Inflation Rate in Germany": "2.2%", "Consumer Price Index in Germany": "130", "Producer Price Index in Germany": "120" },
    { "Inflation Rate in Australia": "3.5%", "Consumer Price Index in Australia": "140", "Producer Price Index in Australia": "130" },
    { "Crime Rate in USA": "680/100,000", "Violent Crime Rate in USA": "480/100,000", "Property Crime Rate in USA": "3,100/100,000" },
    { "Crime Rate in Canada": "670/100,000", "Violent Crime Rate in Canada": "400/100,000", "Property Crime Rate in Canada": "3,000/100,000" },
    { "Crime Rate in UK": "750/100,000", "Violent Crime Rate in UK": "600/100,000", "Property Crime Rate in UK": "2,500/100,000" },
    { "Crime Rate in Germany": "600/100,000", "Violent Crime Rate in Germany": "400/100,000", "Property Crime Rate in Germany": "2,000/100,000" },
    { "Crime Rate in Australia": "800/100,000", "Violent Crime Rate in Australia": "500/100,000", "Property Crime Rate in Australia": "2,800/100,000" },
    { "Average House Price in USA": "$500,000", "Median Rent in USA": "$3,000/month", "Home Ownership Rate in USA": "75%" },
    { "Average House Price in Canada": "$600,000", "Median Rent in Canada": "$2,500/month", "Home Ownership Rate in Canada": "70%" },
    { "Average House Price in UK": "$450,000", "Median Rent in UK": "$2,000/month", "Home Ownership Rate in UK": "80%" },
    { "Average House Price in Germany": "$350,000", "Median Rent in Germany": "$1,500/month", "Home Ownership Rate in Germany": "65%" },
    { "Average House Price in Australia": "$700,000", "Median Rent in Australia": "$3,000/month", "Home Ownership Rate in Australia": "75%" },
    { "Average Commute Time in USA": "50 minutes", "Public Transport Usage in USA": "20%", "Car Ownership Rate in USA": "60%" },
    { "Average Commute Time in Canada": "45 minutes", "Public Transport Usage in Canada": "25%", "Car Ownership Rate in Canada": "65%" },
    { "Average Commute Time in UK": "60 minutes", "Public Transport Usage in UK": "30%", "Car Ownership Rate in UK": "55%" },
    { "Average Commute Time in Germany": "35 minutes", "Public Transport Usage in Germany": "40%", "Car Ownership Rate in Germany": "50%" },
    { "Average Commute Time in Australia": "40 minutes", "Public Transport Usage in Australia": "15%", "Car Ownership Rate in Australia": "70%" },
    { "Life Satisfaction in USA": "5.0", "Happiness Index in USA": "5.5", "Well-being Index in USA": "6.0" },
    { "Life Satisfaction in Canada": "6.0", "Happiness Index in Canada": "6.5", "Well-being Index in Canada": "6.0" },
    { "Life Satisfaction in UK": "5.5", "Happiness Index in UK": "5.5", "Well-being Index in UK": "6.0" },
    { "Life Satisfaction in Germany": "4.8", "Happiness Index in Germany": "5.0", "Well-being Index in Germany": "5.0" },
    { "Life Satisfaction in Australia": "6.6", "Happiness Index in Australia": "6.4", "Well-being Index in Australia": "7.0" }
]

const namelist=['Compare-Bar-Color.png','Compare-Bar-Mark.png','Compare-Bar-Opacity.png','Compare-Bar-Text.png','Compare-Line-Color.png','Compare-Line-Mark.png','Compare-Line-Opacity.png','Compare-Line-Text.png','Compare-Scatter-Color.png','Compare-Scatter-Mark.png','Compare-Scatter-Opacity.png','Compare-Scatter-Text.png','Filter-Bar-Bound.png','Filter-Bar-Color.png','Filter-Bar-Line.png','Filter-Bar-Opacity.png','Filter-Bar-Shade.png','Filter-Line-Bound.png','Filter-Line-Color.png','Filter-Line-Line.png','Filter-Line-Opacity.png','Filter-Line-Shade.png','Filter-Scatter-Bound.png','Filter-Scatter-Color.png','Filter-Scatter-Line.png','Filter-Scatter-Opacity.png','Filter-Scatter-Shade.png','Range-Bar-Bound.png','Range-Bar-Color.png','Range-Bar-Line.png','Range-Bar-Opacity.png','Range-Bar-Shade.png','Range-Line-Bound.png','Range-Line-Color.png','Range-Line-Line.png','Range-Line-Opacity.png','Range-Line-Shade.png','Range-Scatter-Bound.png','Range-Scatter-Color.png','Range-Scatter-Line.png','Range-Scatter-Opacity.png','Range-Scatter-Shade.png','RetrieveValue-Bar-Color.png','RetrieveValue-Bar-Line.png','RetrieveValue-Bar-Mark.png','RetrieveValue-Bar-Opacity.png','RetrieveValue-Bar-Text.png','RetrieveValue-Line-Color.png','RetrieveValue-Line-Line.png','RetrieveValue-Line-Mark.png','RetrieveValue-Line-Opacity.png','RetrieveValue-Line-Text.png','RetrieveValue-Scatter-Color.png','RetrieveValue-Scatter-Line.png','RetrieveValue-Scatter-Mark.png','RetrieveValue-Scatter-Opacity.png','RetrieveValue-Scatter-Text.png','Trend-Bar-Bound.png','Trend-Bar-Color.png','Trend-Bar-Line.png','Trend-Bar-Mark.png','Trend-Bar-Opacity.png','Trend-Bar-Shade.png','Trend-Bar-Text.png','Trend-Line-Bound.png','Trend-Line-Color.png','Trend-Line-Line.png','Trend-Line-Mark.png','Trend-Line-Opacity.png','Trend-Line-Shade.png','Trend-Line-Text.png','Trend-Scatter-Bound.png','Trend-Scatter-Color.png','Trend-Scatter-Line.png','Trend-Scatter-Mark.png','Trend-Scatter-Opacity.png','Trend-Scatter-Shade.png','Trend-Scatter-Text.png']